version: '3.8'

services:
  charger-base:
    image: charger_base:0.1-SNAPHSOT
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: 1000:1000
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
