version: '3.8'

services:
  charger-base:
    image: charger_base:0.1-SNAPHSOT
    build:
      context: ..
      dockerfile: docker/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.apps == true
